hooks: {}
git:
  changelog: git log --pretty=format:"* %s (%h)" ${from}...${to}
  requireCleanWorkingDir: true
  requireBranch: false
  requireUpstream: true
  requireCommits: false
  addUntrackedFiles: false
  commit: true
  commitMessage: Release ${version}
  commitArgs: []
  tag: true
  tagName:
  tagAnnotation: Release ${version}
  tagArgs: []
  push: true
  pushArgs:
    - '--follow-tags'
  pushRepo: ''
npm:
  publish: false
  # publish: true
  publishPath: '.'
  tag:
  otp:
  ignoreVersion: false
  skipChecks: false
github:
  release: true
  releaseName: Release ${version}
  releaseNotes:
  preRelease: false
  draft: false
  tokenRef: GITHUB_TOKEN
  assets:
  host:
  timeout: 0
  proxy:
  skipChecks: false
gitlab:
  release: false
  releaseName: Release ${version}
  releaseNotes:
  tokenRef: GITLAB_TOKEN
  assets:
  origin:
  skipChecks: false
