hooks:
  'after:bump': 'npx auto-changelog -p'
git:
  # changelog: git log --pretty=format:"* %s (%h)" ${from}...${to}
  # 'changelog': 'npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs'
  requireCleanWorkingDir: true
  requireBranch: false
  requireUpstream: true
  requireCommits: false
  addUntrackedFiles: false
  commit: true
  commitMessage: Release ${version}
  commitArgs: []
  tag: true
  tagName:
  tagAnnotation: Release ${version}
  tagArgs: []
  push: true
  pushArgs:
    - '--follow-tags'
  pushRepo: ''
npm:
  publish: false
github:
  release: false
gitlab:
  release: false
plugins:
  '@release-it/conventional-changelog':
    preset: angular
    infile: CHANGELOG.md
#   '@release-it/keep-a-changelog':
#     filename: CHANGELOG.md
