hooks:
  # before:init:
  # - npm run lint
  # - npm test
  # after:my-plugin:bump: './bin/my-script.sh'
  after:bump:
    - npx auto-changelog -p --stdout --commit-limit false --hide-credit --template keepachangelog.hbs
    # - git add CHANGELOG.md
    # - npm run build
  # after:git:release: echo After git push, before github release
  after:release: echo Successfully released ${name} v${version} to ${repo.repository}.
git:
  changelog: git log --pretty=format:"* %s (%h)" ${from}...${to}
  requireCleanWorkingDir: true
  requireBranch: master
  requireUpstream: true
  requireCommits: false
  addUntrackedFiles: false
  commit: true
  commitMessage: 'chore: release ${version}'
  commitArgs: []
  tag: true
  tagName:
  tagAnnotation: Release ${version}
  tagArgs: []
  push: true
  pushArgs:
    - '--follow-tags'
  pushRepo: ''
npm:
  publish: false
github:
  release: false
gitlab:
  release: false
